// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc293.EKIPS.commands;

import org.usfirst.frc293.EKIPS.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class DriveUntilDistance extends Command {

	  private double m_setpoint;

	    public DriveUntilDistance(double setpoint) {
	        m_setpoint = setpoint;
	        requires(Robot.driveBase);
	    }

	    protected void initialize() {
	        Robot.driveBase.enable();
	        Robot.driveBase.setSetpoint(m_setpoint);
	    }

	    protected void execute() {
	    }

	    protected boolean isFinished() {
	        return Robot.driveBase.onTarget();
	    }

	    protected void end() {
	    	Robot.driveBase.disable();
	    	System.out.println("DONE");
	    }

	    protected void interrupted() {
	    }
}
